site_name: Awesome AWS Workshops
repo_name: dgomesbr/awesome-aws-workshops
repo_url: https://github.com/dgomesbr/awesome-aws-workshops
edit_uri: "" # disable edit icon from theme
site_author: Diego Magalhaes, Enrico Bergamo
#copyright: This is NOT an official AWS website and has no affiliation with Amazon Web Services.<br> Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 4.0 International license.
copyright: This is NOT an official AWS website and has no affiliation with Amazon Web Services.<br>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

extra_css:
  - assets/css/extra.css
nav:
  - "Every workshop at your hands, build on! <br/><br/><a href='https://twitter.com/awsomeworkshops'><img alt='follow-social' src='https://img.shields.io/twitter/follow/awsomeworkshops?style=social'></a>": "index.md"
theme:
  name: material
  language: en
  custom_dir: custom/
  features:
    #    - tabs
    - instant
  palette:
    primary: orange
    accent: indigo
  favicon: assets/img/favicon.ico
  icon:
    logo: material/cloud
    repo: material/git
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dgomesbr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dgomesbr
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/diegomagalhaes/
  manifest: manifest.webmanifest
markdown_extensions:
  - extra
  - admonition
  - footnotes
  - meta
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.magiclink
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
  - mdx_truly_sane_lists
plugins:
  - search
  - minify:
      minify_html: true
  # - htmlproofer
  - awesome-pages
  #- pdf-export:
  #    verbose: false
  #    media_type: print
  #    combined: true
  #    combined_output_path: ./AWSome-aws-workshops.pdf
